import os
import uuid
import logging
from core.memory.schema import get_engine, Base
from core.engine.pipeline import TrainingPipeline
from core.engine.models.xgboost_trainer import XGBoostTrainer
from core.engine.models.sklearn_trainers import LogisticRegressionTrainer
from core.reporting.dashboard import DashboardGenerator

logging.basicConfig(level=logging.INFO)

def run():
    # Setup mock DB for local dev testing
    db_url = os.environ.get("GLOBALPULSE_DB_URL", "sqlite:///globalpulse_dev.db")
    engine = get_engine(db_url)
    Base.metadata.create_all(engine)
    
    # 1. Pipeline Orchestrator
    pipeline = TrainingPipeline(engine, dataset_dir="datasets")
    
    # We will use dummy parquet files generated by Phase 2.5
    # If they don't exist, we will create empty stubs to allow the pipeline to run and log properly.
    if not os.path.exists("datasets"):
        os.makedirs("datasets")
    
    import pandas as pd
    import numpy as np
    
    # Creating a dummy dataset to verify the pipeline doesn't crash
    dummy_df = pd.DataFrame({
        'id': [f"m_{i}" for i in range(100)],
        'outcome': ['team_a' if np.random.rand() > 0.5 else 'team_b' for _ in range(100)],
        'team_a_id': ['team_a'] * 100,
        'team_b_id': ['team_b'] * 100,
        'year': [2010] * 100
    })
    
    train_file = "train_2010_2010.parquet"
    test_file = "test_2011_2011.parquet"
    dummy_df.to_parquet(os.path.join("datasets", train_file))
    dummy_df.to_parquet(os.path.join("datasets", test_file))
    
    # 2. Run the Experiment
    experiment_id = f"exp_{str(uuid.uuid4())[:8]}"
    
    try:
        pipeline.run_experiment(
            experiment_id=experiment_id,
            train_files=[train_file],
            test_files=[test_file],
            trainers=[LogisticRegressionTrainer(), XGBoostTrainer()],
            feature_families=["stats_only", "all_features"]
        )
        
        # 3. Generate the Dashboard
        dashboard = DashboardGenerator(engine, "reports")
        report_path = dashboard.generate_experiment_report(experiment_id)
        
        logging.info(f"Local dev run complete! Report generated at: {report_path}")
    except Exception as e:
        logging.error(f"Pipeline failed: {e}")

if __name__ == "__main__":
    run()
