"""Initial baseline

Revision ID: 810f59a2434a
Revises: 
Create Date: 2026-07-09 10:39:11.064160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810f59a2434a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feature_vectors', 'embedding',
               existing_type=sa.NUMERIC(precision=1536),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('model_registry', 'model_artifact_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('model_registry', 'is_champion',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('model_registry', 'feature_families',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_registry', 'feature_families',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('model_registry', 'is_champion',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('model_registry', 'model_artifact_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('feature_vectors', 'embedding',
               existing_type=sa.String(),
               type_=sa.NUMERIC(precision=1536),
               existing_nullable=True)
    # ### end Alembic commands ###
