import DashboardLayout from '../layouts/DashboardLayout'
import { useHistory } from '../hooks/useApi'
import { TableSkeleton } from '../components/ui/Skeleton'
import { fmtDateTime } from '../utils/format'

function ComingSoon({ feature }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: 300, color: '#94a3b8' }}>
      <div style={{ fontSize: 48, marginBottom: 16 }}>🚧</div>
      <h3 style={{ fontSize: 18, color: '#64748b', marginBottom: 8 }}>{feature}</h3>
      <p style={{ fontSize: 13, maxWidth: 400, textAlign: 'center' }}>
        This module is currently disconnected from the production backend.<br />
        Awaiting Phase 2 implementation.
      </p>
    </div>
  )
}

export function PatternMemoryPage() {
  return (
    <DashboardLayout title="Pattern Memory" subtitle="Nearest historical match patterns and embedding similarity">
      <div className="card"><ComingSoon feature="Pattern Memory Engine" /></div>
    </DashboardLayout>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Historical Replay Page — Completed matches with VERIFIED outcomes
// Phase 15: Pure data rendering. No manual frontend probability/winner calculations.
// ─────────────────────────────────────────────────────────────────────────────
export function HistoricalReplayPage() {
  const { data: history, isLoading, isError } = useHistory()

  return (
    <DashboardLayout title="Historical Replay" subtitle="Completed and verified match predictions">
      <div className="card">
        <div style={{ marginBottom: 16 }}>
          <h3 style={{ fontSize: 14, fontWeight: 600 }}>Completed Matches Audit Trail</h3>
          <p style={{ fontSize: 12, color: '#94a3b8', marginTop: 2 }}>Verified outcomes from prediction_store</p>
        </div>
        {isLoading ? <TableSkeleton rows={10} /> : (
          <table className="gp-table">
            <thead>
              <tr>
                <th>Match</th>
                <th>Date & Time (UTC)</th>
                <th>Venue</th>
                <th>Predicted Winner</th>
                <th>Win Prob</th>
                <th>Actual Winner</th>
                <th>Result</th>
              </tr>
            </thead>
            <tbody>
              {(Array.isArray(history) ? history : []).map((m, i) => {
                // Read directly from the joined fields generated by endpoints.js
                // No fabricated 0.5 fallbacks or team comparisons
                const predicted = m.predicted_winner_id || '—'
                const actual = m.actual_winner_id || '—'
                const isCorrect = m.is_correct

                return (
                  <tr key={i}>
                    <td>
                      <span style={{ fontWeight: 600 }}>{m.team_a || '?'}</span> <span style={{ color: '#94a3b8' }}>vs</span> <span style={{ fontWeight: 600 }}>{m.team_b || '?'}</span>
                    </td>
                    <td style={{ color: '#64748b', whiteSpace: 'nowrap' }}>{fmtDateTime(m.date)}</td>
                    <td style={{ color: '#475569', fontWeight: 500 }}>{m.venue || '—'}</td>
                    <td style={{ fontWeight: 600, color: '#3b5bdb' }}>{predicted}</td>
                    <td>
                      <strong>
                        {m.probability != null ? `${(m.probability * 100).toFixed(1)}%` : '—'}
                      </strong>
                    </td>
                    <td style={{ fontWeight: 600, color: '#0f172a' }}>{actual}</td>
                    <td>
                      {isCorrect === true && <span className="badge badge-success">✓ Correct</span>}
                      {isCorrect === false && <span className="badge badge-danger">✗ Wrong</span>}
                      {isCorrect === null && <span className="badge badge-warn">Pending</span>}
                    </td>
                  </tr>
                )
              })}
              {(!Array.isArray(history) || history.length === 0) && (
                <tr>
                  <td colSpan={7} style={{ textAlign: 'center', color: '#94a3b8', padding: '40px 0' }}>
                    No verified completed matches found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        )}
      </div>
    </DashboardLayout>
  )
}

export function ResearchPage() {
  return (
    <DashboardLayout title="Research" subtitle="Deep-dive analysis: Calibration, SHAP, ROC, Confusion Matrix">
      <div className="card"><ComingSoon feature="Research & Analysis Hub" /></div>
    </DashboardLayout>
  )
}

export function AlertsPage() {
  return (
    <DashboardLayout title="Alerts" subtitle="Prediction alerts and notification settings">
      <div className="card"><ComingSoon feature="Alerts System" /></div>
    </DashboardLayout>
  )
}

export function SettingsPage() {
  const apiUrl = import.meta.env.VITE_SUPABASE_URL || 'Not configured'
  return (
    <DashboardLayout title="Settings" subtitle="System configuration and API access">
      <div className="card">
        <h3 style={{ fontSize: 14, fontWeight: 600, marginBottom: 16 }}>Current Configuration</h3>
        <table className="gp-table">
          <tbody>
            <tr>
              <td style={{ color: '#64748b', width: 200 }}>Supabase URL</td>
              <td style={{ fontFamily: 'monospace', fontSize: 12, color: '#3b5bdb' }}>{apiUrl}</td>
            </tr>
            <tr>
              <td style={{ color: '#64748b' }}>Frontend Version</td>
              <td style={{ fontWeight: 600 }}>GlobalPulse Production (React + Vite)</td>
            </tr>
            <tr>
              <td style={{ color: '#64748b' }}>Status</td>
              <td><span className="badge badge-success">Forensic Audit Passed</span></td>
            </tr>
          </tbody>
        </table>
      </div>
    </DashboardLayout>
  )
}
